# Generated by Django 3.1.14 on 2023-03-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230301_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
