# Generated by Django 3.1.14 on 2023-03-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230302_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Jobseeker',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_jobseeker',
        ),
    ]
