# Generated by Django 3.1.14 on 2023-03-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230304_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
