# Generated by Django 3.1.14 on 2023-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230304_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='cover_photo/'),
        ),
    ]
